# InfluxDB + Grafana compose file. 
# With data persistency
version: '3'

services:
  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - "8086:8086"
      - "2003:2003"
    environment:
      INFLUXDB_DB: "testproject"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: pass
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
      INFLUXDB_GRAPHITE_ENABLED: "false"
    volumes:
      - /var/lib/docker/volumes:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_PATHS_PROVISIONING: "/grafana/provisioning"
    user: "0"
    links:
      - influxdb
    volumes:
      - /var/lib/docker/volumes:/var/lib/grafana
      - ./grafana:/grafana

  chronograf:
      image: chronograf:latest
      links:
      - influxdb
      volumes:
      - /var/lib/docker/volumes:/var/lib/grafana
      ports:
      - "8087:8888"
